### ISSUE TITLE
function testing is missing

### ISSUE THREAD

**Issue by EnricoGiampieri** [JustWhit3/higgs-decay-classification#2]
None of the functions defined have any sort of testing to make sure that what the do is conform with their declared goal

**Comment by JustWhit3** [comment]
This is the last commit for the solution of the "testing problem": https://github.com/JustWhit3/Software_and_Computing_program/commit/fd4725f9317be90f7cb03c41201e895e1d164e29.
I successfully tested 5/7 of the defined functions. I've had problem to test "splitting_jets" and "make_model" functions (in particular the last one, due to the fact that it returns a "keras" object and I was not sure on how to test this).
I've added in the un-successfully tested functions my trial for the testing problem (at the bottom of the function definition code) even if it doesn't work, so maybe this can be useful for you to see how I tried to proceed.
